const $ = id => document.getElementById(id);
let products=[];
let editingId=null;
let selectedImageData='';
const fallbackImage='https://raw.githubusercontent.com/Amitbhai-2152/Vishwakarma-Enterprises/main/images/shop3.jpeg';
const fallbackProducts=[{id:'P001',category:'plumbing',brand:'Supreme',image:fallbackImage,name:{hi:'PVC पाइप',en:'PVC Pipe'},description:{hi:'मजबूत और भरोसेमंद प्लंबिंग पाइप।',en:'Strong and reliable plumbing pipe.'},mrp:0,features:{hi:[],en:[]},specifications:{hi:{},en:{}},featured:true},{id:'P002',category:'water',brand:'Your Brand',image:fallbackImage,name:{hi:'पानी की टंकी',en:'Water Tank'},description:{hi:'घर और व्यवसाय के लिए मजबूत पानी भंडारण समाधान।',en:'Durable water storage solution for home and business.'},mrp:0,features:{hi:[],en:[]},specifications:{hi:{},en:{}},featured:true}];
const AUTH_KEY='ve-github-auth';
function authState(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')||{}}catch{return {}}}
function clearAuth(){localStorage.removeItem(AUTH_KEY);localStorage.removeItem('ve-github-token')}
async function refreshAccessToken(){const a=authState();if(!a.refresh_token)return '';try{const body=new URLSearchParams({client_id:window.ADMIN_CONFIG.githubClientId,grant_type:'refresh_token',refresh_token:a.refresh_token});const r=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json().catch(()=>({}));if(!r.ok||data.error||!data.access_token){clearAuth();return ''}localStorage.setItem(AUTH_KEY,JSON.stringify({...a,...data,stored_at:Date.now()}));localStorage.setItem('ve-github-token',data.access_token);return data.access_token}catch{return ''}}
async function token(){const a=authState();if(a.access_token){const age=Math.max(0,Date.now()-(a.stored_at||0)),life=(a.expires_in||28800)*1000;if(!a.expires_in||age<Math.max(0,life-120000))return a.access_token}return refreshAccessToken()}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),3200)}
function stats(){const plumbing=products.filter(p=>p.category==='plumbing').length;$('totalCount').textContent=products.length;$('popularCount').textContent=products.filter(p=>p.featured).length;$('plumbingCount').textContent=plumbing;$('otherCount').textContent=Math.max(0,products.length-plumbing)}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function formatMrp(v){const n=Number(v);return Number.isFinite(n)&&n>0?`₹${n.toLocaleString('en-IN',{minimumFractionDigits:n%1?2:0,maximumFractionDigits:2})}`:''}
function render(){const q=$('searchInput').value.trim().toLowerCase(),cat=$('categoryFilter').value,pop=$('popularOnly').checked;const list=products.filter(p=>{const t=[p.id,p.brand,p.category,p.name?.hi,p.name?.en,p.description?.hi,p.description?.en,String(p.mrp||''),(p.features?.hi||[]).join(' '),(p.features?.en||[]).join(' '),Object.keys(p.specifications?.hi||{}).join(' '),Object.keys(p.specifications?.en||{}).join(' '),Object.values(p.specifications?.hi||{}).join(' '),Object.values(p.specifications?.en||{}).join(' ')].join(' ').toLowerCase();return(!q||t.includes(q))&&(cat==='all'||p.category===cat)&&(!pop||p.featured)});$('productsGrid').innerHTML=list.map(p=>`<article class="product-item"><img src="${esc(p.image||fallbackImage)}" alt="${esc(p.name?.en||'Product')}" onerror="this.onerror=null;this.src='${fallbackImage}'"><div class="product-body"><div class="product-meta"><span>${esc(p.category||'—')}</span>${p.featured?'<span class="badge">Popular</span>':''}</div><h3>${esc(p.name?.en||p.name?.hi||p.id)}</h3><p>${esc(p.description?.en||p.description?.hi||'')}</p>${formatMrp(p.mrp)?`<div class="product-mrp">MRP <strong>${formatMrp(p.mrp)}</strong></div>`:''}<div class="item-actions"><button class="edit" data-edit="${esc(p.id)}">Edit</button><button data-delete="${esc(p.id)}">Delete</button></div></div></article>`).join('');$('emptyState').hidden=list.length!==0;stats()}
function lines(v){return Array.isArray(v)?v.join('\n'):String(v||'')}
function parseLines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function specsText(v){return Object.entries(v&&typeof v==='object'?v:{}).map(([k,val])=>`${k}: ${val}`).join('\n')}
function parseSpecs(v){const out={};parseLines(v).forEach(line=>{const i=line.indexOf(':');if(i>0){const k=line.slice(0,i).trim(),val=line.slice(i+1).trim();if(k&&val)out[k]=val}});return out}
function openEditor(p=null){editingId=p?.id||null;$('dialogTitle').textContent=editingId?'Edit Product':'Add Product';$('productId').value=p?.id||`P${String(products.length+1).padStart(3,'0')}`;$('brand').value=p?.brand||'';$('nameHi').value=p?.name?.hi||'';$('nameEn').value=p?.name?.en||'';$('category').value=p?.category||'plumbing';$('sizes').value=Array.isArray(p?.sizes)?p.sizes.join(', '):p?.sizes||'';$('mrp').value=p?.mrp??'';$('descriptionHi').value=p?.description?.hi||'';$('descriptionEn').value=p?.description?.en||'';$('featuresHi').value=lines(p?.features?.hi);$('featuresEn').value=lines(p?.features?.en);$('specificationsHi').value=specsText(p?.specifications?.hi);$('specificationsEn').value=specsText(p?.specifications?.en);$('featured').checked=!!p?.featured;selectedImageData='';$('imageInput').value='';$('imagePreview').src=p?.image||'';$('imagePreview').hidden=!p?.image;$('imageHint').textContent=p?.image?'Current image kept unless you select a new one.':'Choose a product photo.';$('productDialog').showModal()}
function imageData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1200,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
$('imageInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>12*1024*1024){toast('Please choose an image smaller than 12 MB.');e.target.value='';return}try{selectedImageData=await imageData(f);$('imagePreview').src=selectedImageData;$('imagePreview').hidden=false;$('imageHint').textContent='Image prepared and resized. Publish to send it to GitHub.'}catch{toast('Could not read that image.')}});
$('newProductBtn').onclick=()=>openEditor();$('closeDialog').onclick=()=>$('productDialog').close();$('cancelBtn').onclick=()=>$('productDialog').close();
$('productsGrid').addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),dl=e.target.closest('[data-delete]');if(ed){const p=products.find(x=>x.id===ed.dataset.edit);if(p)openEditor(p)}if(dl){const id=dl.dataset.delete;if(!confirm(`Delete ${id} from the catalogue draft?`))return;products=products.filter(x=>x.id!==id);saveDraft();render();toast('Removed from the current draft. Publish to make it live.')}});
$('searchInput').oninput=render;$('categoryFilter').onchange=render;$('popularOnly').onchange=render;$('refreshBtn').onclick=async()=>{localStorage.removeItem('ve-admin-draft');await loadCatalogue()};
$('productForm').addEventListener('submit',e=>{e.preventDefault();const previous=products.find(p=>p.id===editingId);const rawMrp=$('mrp').value.trim();const mrp=rawMrp===''?0:Number(rawMrp);if(rawMrp!==''&&(!Number.isFinite(mrp)||mrp<0)){toast('Please enter a valid MRP.');$('mrp').focus();return}const product={id:$('productId').value.trim(),brand:$('brand').value.trim(),category:$('category').value,name:{hi:$('nameHi').value.trim(),en:$('nameEn').value.trim()},description:{hi:$('descriptionHi').value.trim(),en:$('descriptionEn').value.trim()},features:{hi:parseLines($('featuresHi').value),en:parseLines($('featuresEn').value)},specifications:{hi:parseSpecs($('specificationsHi').value),en:parseSpecs($('specificationsEn').value)},sizes:$('sizes').value.split(',').map(x=>x.trim()).filter(Boolean),mrp, image:selectedImageData||previous?.image||fallbackImage,featured:$('featured').checked};if(!product.id||!product.name.hi||!product.name.en){toast('Please fill Product ID and both names.');return}if(products.some(p=>p.id===product.id&&p.id!==editingId)){toast('That Product ID already exists.');return}products=editingId?products.map(p=>p.id===editingId?product:p):[product,...products];saveDraft();render();$('productDialog').close();toast('Draft saved. Click Publish to update the public catalogue.')});
function saveDraft(){localStorage.setItem('ve-admin-draft',JSON.stringify(products))}
function authHeaders(t){return{Authorization:'Bearer '+t,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'}}
function encodeBase64(text){return btoa(unescape(encodeURIComponent(text)))}
async function getRemoteFile(path){const t=await token();if(!t)throw Object.assign(new Error('GitHub login is required.'),{code:'AUTH_REQUIRED'});const r=await fetch(`https://api.github.com/repos/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/contents/${path}?ref=main`,{headers:authHeaders(t),cache:'no-store'});if(r.status===401){clearAuth();throw Object.assign(new Error('GitHub login expired. Please sign in again.'),{code:'AUTH_REQUIRED'})}if(r.status===404)return null;if(!r.ok)throw new Error(r.status===403?'The GitHub App is not authorized for this repository. Check the App installation.':`GitHub returned ${r.status}.`);return r.json()}
async function putRepoFile(path,content,sha,message){const t=await token();if(!t)throw Object.assign(new Error('GitHub login is required.'),{code:'AUTH_REQUIRED'});const body={message,content:encodeBase64(content),branch:'main'};if(sha)body.sha=sha;const r=await fetch(`https://api.github.com/repos/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/contents/${path}`,{method:'PUT',headers:authHeaders(t),body:JSON.stringify(body)});if(r.status===401){clearAuth();throw Object.assign(new Error('GitHub login expired.'),{code:'AUTH_REQUIRED'})}if(!r.ok){let detail='GitHub publish failed.';try{const j=await r.json();detail=j.message||detail}catch{}throw new Error(detail)}return r.json()}
async function uploadImage(product){if(!selectedImageData?.startsWith('data:image/'))return product.image;const path=`images/products/${String(product.id).replace(/[^a-zA-Z0-9_-]/g,'-')}.jpg`;const existing=await getRemoteFile(path);const t=await token();if(!t)throw Object.assign(new Error('GitHub login is required.'),{code:'AUTH_REQUIRED'});const body={message:`Update product image ${product.id}`,content:selectedImageData.split(',')[1],branch:'main'};if(existing?.sha)body.sha=existing.sha;const r=await fetch(`https://api.github.com/repos/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/contents/${path}`,{method:'PUT',headers:authHeaders(t),body:JSON.stringify(body)});if(r.status===401){clearAuth();throw Object.assign(new Error('GitHub login expired.'),{code:'AUTH_REQUIRED'})}if(!r.ok){let detail='Image upload failed.';try{const j=await r.json();detail=j.message||detail}catch{}throw new Error(detail)}return `https://raw.githubusercontent.com/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/main/${path}`}
async function publish(){const t=await token();if(!t){location.href='setup.html?return=products';return}const button=$('publishBtn');button.disabled=true;button.textContent='Publishing…';try{const current=await getRemoteFile(window.ADMIN_CONFIG.dataPath);const next=JSON.parse(JSON.stringify(products));if(selectedImageData){const p=editingId?next.find(x=>x.id===editingId):next.find(x=>x.image===selectedImageData);if(p)p.image=await uploadImage(p)}await putRepoFile(window.ADMIN_CONFIG.dataPath,JSON.stringify(next,null,2)+'\n',current?.sha,`Update product catalogue (${next.length} products)`);products=next;selectedImageData='';localStorage.removeItem('ve-admin-draft');$('connectionStatus').textContent='Connected';$('connectionStatus').className='status-pill online';render();toast(`Published ${next.length} product${next.length===1?'':'s'} successfully.`)}catch(error){if(error?.code==='AUTH_REQUIRED'){location.href='setup.html?return=products';return}$('connectionStatus').textContent='Publish failed';$('connectionStatus').className='status-pill offline';toast(error.message||'Publish failed. No change was confirmed.')}finally{button.disabled=false;button.textContent='Publish Changes'}}
$('publishBtn')?.addEventListener('click',publish);
async function loadCatalogue(){try{const d=localStorage.getItem('ve-admin-draft');if(d){products=JSON.parse(d);const connected=!!(await token());$('connectionStatus').textContent=connected?'Draft ready':'Draft mode';$('connectionStatus').className='status-pill online';render();return}const r=await fetch(window.ADMIN_CONFIG.dataUrl+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();products=Array.isArray(data)&&data.length?data:fallbackProducts;const connected=!!(await token());$('connectionStatus').textContent=connected?'Connected':'Read-only';$('connectionStatus').className='status-pill online';render()}catch{products=[...fallbackProducts];$('connectionStatus').textContent='Read-only fallback';$('connectionStatus').className='status-pill offline';render()}}
loadCatalogue();