const $=id=>document.getElementById(id);let products=[];let editingId=null;let selectedImageData='';
const fallbackImage='https://raw.githubusercontent.com/Amitbhai-2152/Vishwakarma-Enterprises/main/images/shop3.jpeg';
const fallbackProducts=[{id:'P001',category:'plumbing',brand:'Supreme',image:fallbackImage,name:{hi:'PVC पाइप',en:'PVC Pipe'},description:{hi:'मजबूत और भरोसेमंद प्लंबिंग पाइप।',en:'Strong and reliable plumbing pipe.'},featured:true},{id:'P002',category:'water',brand:'Your Brand',image:fallbackImage,name:{hi:'पानी की टंकी',en:'Water Tank'},description:{hi:'घर और व्यवसाय के लिए मजबूत पानी भंडारण समाधान।',en:'Durable water storage solution for home and business.'},featured:true}];
const TOKEN_KEY='ve-github-token';
function token(){return localStorage.getItem(TOKEN_KEY)||''}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),3200)}
function stats(){const plumbing=products.filter(p=>p.category==='plumbing').length;$('totalCount').textContent=products.length;$('popularCount').textContent=products.filter(p=>p.featured).length;$('plumbingCount').textContent=plumbing;$('otherCount').textContent=Math.max(0,products.length-plumbing)}
function render(){const q=$('searchInput').value.trim().toLowerCase(),cat=$('categoryFilter').value,pop=$('popularOnly').checked;const list=products.filter(p=>{const t=[p.id,p.brand,p.category,p.name?.hi,p.name?.en,p.description?.hi,p.description?.en].join(' ').toLowerCase();return(!q||t.includes(q))&&(cat==='all'||p.category===cat)&&(!pop||p.featured)});$('productsGrid').innerHTML=list.map(p=>`<article class="product-item"><img src="${p.image||fallbackImage}" alt="${p.name?.en||'Product'}" onerror="this.onerror=null;this.src='${fallbackImage}'"><div class="product-body"><div class="product-meta"><span>${p.category||'—'}</span>${p.featured?'<span class="badge">Popular</span>':''}</div><h3>${p.name?.en||p.name?.hi||p.id}</h3><p>${p.description?.en||p.description?.hi||''}</p><div class="item-actions"><button class="edit" data-edit="${p.id}">Edit</button><button data-delete="${p.id}">Delete</button></div></div></article>`).join('');$('emptyState').hidden=list.length!==0;stats()}
function openEditor(p=null){editingId=p?.id||null;$('dialogTitle').textContent=editingId?'Edit Product':'Add Product';$('productId').value=p?.id||`P${String(products.length+1).padStart(3,'0')}`;$('brand').value=p?.brand||'';$('nameHi').value=p?.name?.hi||'';$('nameEn').value=p?.name?.en||'';$('category').value=p?.category||'plumbing';$('sizes').value=Array.isArray(p?.sizes)?p.sizes.join(', '):p?.sizes||'';$('descriptionHi').value=p?.description?.hi||'';$('descriptionEn').value=p?.description?.en||'';$('featured').checked=!!p?.featured;selectedImageData=p?.image||'';$('imagePreview').src=selectedImageData;$('imagePreview').hidden=!selectedImageData;$('imageHint').textContent=selectedImageData?'Current image kept unless you select a new one.':'Choose a product photo.';$('productDialog').showModal()}
function imageData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1200,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
$('imageInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{selectedImageData=await imageData(f);$('imagePreview').src=selectedImageData;$('imagePreview').hidden=false;$('imageHint').textContent='Image prepared and resized.'}catch{toast('Could not read that image.')}});
$('newProductBtn').onclick=()=>openEditor();$('closeDialog').onclick=()=>$('productDialog').close();$('cancelBtn').onclick=()=>$('productDialog').close();
$('productsGrid').addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),dl=e.target.closest('[data-delete]');if(ed){const p=products.find(x=>x.id===ed.dataset.edit);if(p)openEditor(p)}if(dl){products=products.filter(x=>x.id!==dl.dataset.delete);saveDraft();render();toast('Removed from this browser draft. Use Publish to commit the change.')}});
$('searchInput').oninput=render;$('categoryFilter').onchange=render;$('popularOnly').onchange=render;$('refreshBtn').onclick=loadCatalogue;
$('productForm').addEventListener('submit',e=>{e.preventDefault();const product={id:$('productId').value.trim(),brand:$('brand').value.trim(),category:$('category').value,name:{hi:$('nameHi').value.trim(),en:$('nameEn').value.trim()},description:{hi:$('descriptionHi').value.trim(),en:$('descriptionEn').value.trim()},sizes:$('sizes').value.split(',').map(x=>x.trim()).filter(Boolean),image:selectedImageData||fallbackImage,featured:$('featured').checked};if(!product.id||!product.name.hi||!product.name.en){toast('Please fill Product ID and both names.');return}if(products.some(p=>p.id===product.id&&p.id!==editingId)){toast('That Product ID already exists.');return}if(!selectedImageData&&editingId)product.image=products.find(p=>p.id===editingId)?.image||fallbackImage;products=editingId?products.map(p=>p.id===editingId?product:p):[product,...products];saveDraft();render();$('productDialog').close();toast('Draft saved. Click Publish to update the public catalogue.')});
function saveDraft(){localStorage.setItem('ve-admin-draft',JSON.stringify(products))}
function authHeaders(){const t=token();return{Authorization:'Bearer '+t,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'}}
async function getCurrentFile(){const r=await fetch(`https://api.github.com/repos/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/contents/${window.ADMIN_CONFIG.dataPath}`,{headers:authHeaders(),cache:'no-store'});if(!r.ok)throw new Error(r.status===401||r.status===403?'GitHub token is invalid or lacks Contents write permission.':`GitHub returned ${r.status}.`);return r.json()}
async function putFile(path,content,sha,message){const body={message,content:btoa(unescape(encodeURIComponent(content))),branch:'main'};if(sha)body.sha=sha;const r=await fetch(`https://api.github.com/repos/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/contents/${path}`,{method:'PUT',headers:authHeaders(),body:JSON.stringify(body)});if(!r.ok){let detail='GitHub publish failed.';try{const j=await r.json();detail=j.message||detail}catch{}throw new Error(detail)}return r.json()}
async function uploadImage(product){if(!selectedImageData||!selectedImageData.startsWith('data:image'))return product.image;const path=`images/products/${product.id}.jpg`;const base64=selectedImageData.split(',')[1];const existing=await fetch(`https://api.github.com/repos/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/contents/${path}`,{headers:authHeaders(),cache:'no-store'});let sha;if(existing.ok)sha=(await existing.json()).sha;const body={message:`Update product image ${product.id}`,content:base64,branch:'main'};if(sha)body.sha=sha;const r=await fetch(`https://api.github.com/repos/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/contents/${path}`,{method:'PUT',headers:authHeaders(),body:JSON.stringify(body)});if(!r.ok){let detail='Image upload failed.';try{const j=await r.json();detail=j.message||detail}catch{}throw new Error(detail)}return `https://raw.githubusercontent.com/${window.ADMIN_CONFIG.repoOwner}/${window.ADMIN_CONFIG.repoName}/main/${path}`}
async function publish(){const t=token();if(!t){location.href='setup.html';return}const button=document.getElementById('publishBtn');button.disabled=true;button.textContent='Publishing…';try{const current=await getCurrentFile();let next=[...products];if(selectedImageData){const index=next.findIndex(p=>p.id===editingId);if(index>=0)next[index].image=await uploadImage(next[index])}const clean=JSON.stringify(next,null,2)+'\n';await putFile(window.ADMIN_CONFIG.dataPath,clean,current.sha,'Update product catalogue');localStorage.removeItem('ve-admin-draft');products=next;selectedImageData='';$('connectionStatus').textContent='Published';$('connectionStatus').className='status-pill online';render();toast('Published successfully. The public catalogue will use the updated data.')}catch(error){toast(error.message||'Publish failed. No changes were confirmed.')}finally{button.disabled=false;button.textContent='Publish Changes'}}
function renderPublishControl(){let wrap=document.querySelector('.top-actions');if(!wrap||document.getElementById('publishBtn'))return;const b=document.createElement('button');b.id='publishBtn';b.className='primary-btn';b.textContent='Publish Changes';b.onclick=publish;wrap.insertBefore(b,wrap.firstChild)}
async function loadCatalogue(){try{renderPublishControl();const d=localStorage.getItem('ve-admin-draft');if(d){products=JSON.parse(d);$('connectionStatus').textContent=token()?'Draft ready to publish':'Draft mode';$('connectionStatus').className='status-pill online';render();return}const r=await fetch(window.ADMIN_CONFIG.dataUrl+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();products=Array.isArray(data)&&data.length?data:fallbackProducts;$('connectionStatus').textContent=token()?'Connected':'Read-only';$('connectionStatus').className='status-pill online';render()}catch{products=[...fallbackProducts];$('connectionStatus').textContent='Offline fallback';$('connectionStatus').className='status-pill offline';render()}}
loadCatalogue();
