(()=>{
  const $=id=>document.getElementById(id);
  let dirty=false,cleanSnapshot='',previewDialog=null;
  const variants=()=>typeof currentVariants!=='undefined'&&Array.isArray(currentVariants)?currentVariants:[];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?`₹${n.toLocaleString('en-IN',{maximumFractionDigits:2})}`:'—'};
  const lines=v=>String(v||'').split(/\r?\n/).map(x=>x.replace(/^\s*[-•▪◦‣]\s*/,'').trim()).filter(Boolean);
  function snapshot(){const ids=['productId','brand','nameHi','nameEn','category','sizes','mrp','descriptionHi','descriptionEn','featuresHi','featuresEn','featured','productStatus'];const o={};ids.forEach(id=>{const e=$(id);o[id]=e?.type==='checkbox'?!!e.checked:String(e?.value||'')});o.variants=variants().map(v=>({name:String(v.name||''),mrp:Number(v.mrp)||0}));return JSON.stringify(o)}
  function setClean(){cleanSnapshot=snapshot();dirty=false;markTitle()}
  function markTitle(){const t=$('dialogTitle');if(t&&$('productDialog')?.open){const base=t.dataset.base||t.textContent.replace(/^•\s*/,'');t.dataset.base=base;t.textContent=dirty?'• '+base:base}}
  function changed(){dirty=snapshot()!==cleanSnapshot;markTitle()}

  function ensureStatus(){const featured=$('featured');if(!featured||$('productStatus'))return;const label=document.createElement('label');label.className='check full';label.innerHTML='<span>Product status</span><select id="productStatus"><option value="active">Active — visible on catalogue</option><option value="hidden">Hidden — not shown on public catalogue</option></select>';featured.closest('label')?.insertAdjacentElement('afterend',label)}

  function ensurePreview(){if(previewDialog)return previewDialog;previewDialog=document.createElement('dialog');previewDialog.id='productPreviewDialog';previewDialog.className='product-preview-dialog';previewDialog.innerHTML='<div class="preview-head"><div><span class="eyebrow">LIVE PREVIEW</span><h2>Public Product Preview</h2></div><button type="button" class="icon-btn" id="closePreview">×</button></div><div id="previewBody" class="preview-body"></div>';document.body.appendChild(previewDialog);$('closePreview').onclick=()=>previewDialog.close();return previewDialog}
  function showPreview(){const p={id:$('productId').value.trim(),brand:$('brand').value.trim(),nameEn:$('nameEn').value.trim(),nameHi:$('nameHi').value.trim(),descriptionEn:$('descriptionEn').value.trim(),variants:variants().filter(v=>String(v.name||'').trim()),features:lines($('featuresEn').value||$('featuresHi').value),image:$('imagePreview').hidden?'':$('imagePreview').src};const d=ensurePreview();d.querySelector('#previewBody').innerHTML=`<article class="public-preview-card"><div>${p.image?`<img class="preview-image" src="${esc(p.image)}" alt="${esc(p.nameEn)}">`:'<div class="preview-image placeholder">No image selected</div>'}</div><section class="public-preview-info"><span>${esc(p.brand||'Vishwakarma Enterprises')}</span><small>${esc(p.id)}</small><h1>${esc(p.nameEn||'Product name')}</h1><p class="preview-hi-name">${esc(p.nameHi||'उत्पाद का नाम')}</p>${p.variants[0]?.mrp?`<div class="preview-mrp"><span>MRP per piece</span><strong>${money(p.variants[0].mrp)}</strong></div>`:''}<p>${esc(p.descriptionEn||'No English description added yet.')}</p>${p.variants.length?`<div class="preview-section"><h3>Sizes / Variants</h3><div class="preview-variants">${p.variants.map(v=>`<span>${esc(v.name)} · ${money(v.mrp)}</span>`).join('')}</div></div>`:''}${p.features.length?`<div class="preview-section"><h3>Key Features</h3><ul>${p.features.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`:''}<button class="primary-btn" type="button" disabled>Enquire on WhatsApp</button></section></article>`;d.showModal()}

  function validate(items){const errors=[],ids=new Set();(Array.isArray(items)?items:[]).forEach((p,i)=>{const where=`Product ${p?.id||'#'+(i+1)}`,id=String(p?.id||'').trim();if(!id)errors.push(`${where}: missing Product ID`);else if(ids.has(id))errors.push(`${where}: duplicate Product ID ${id}`);else ids.add(id);if(!String(p?.name?.en||'').trim())errors.push(`${where}: missing English name`);if(!String(p?.name?.hi||'').trim())errors.push(`${where}: missing Hindi name`);if(!String(p?.category||'').trim())errors.push(`${where}: missing category`);const vs=Array.isArray(p?.sizes)?p.sizes:[];if(!vs.length)errors.push(`${where}: no size/variant`);const names=new Set();vs.forEach(v=>{const name=String(typeof v==='object'?v.name||v.size||'':v).trim(),mrp=Number(typeof v==='object'?v.mrp:p?.mrp);if(!name)errors.push(`${where}: empty size/variant`);else if(names.has(name.toLowerCase()))errors.push(`${where}: duplicate size/variant ${name}`);else names.add(name.toLowerCase());if(!Number.isFinite(mrp)||mrp<0)errors.push(`${where}: invalid MRP for ${name||'variant'}`)});if(!String(p?.image||'').trim())errors.push(`${where}: missing product image`);['hi','en'].forEach(lang=>{const fs=Array.isArray(p?.features?.[lang])?p.features[lang]:[];if(fs.some(x=>!String(x||'').trim()))errors.push(`${where}: empty ${lang} feature`)})});return errors}
  function toastList(errors){const msg=`Publish blocked. ${errors.length} issue${errors.length===1?'':'s'} found:\n\n• ${errors.slice(0,10).join('\n• ')}${errors.length>10?'\n• …more':''}`;typeof toast==='function'?toast(msg):alert(msg)}

  function duplicateProduct(id){if(typeof products==='undefined'||typeof openEditor!=='function')return;const source=products.find(p=>String(p.id)===String(id));if(!source)return;const copy=JSON.parse(JSON.stringify(source));copy.id='';copy.status='active';copy.name={hi:copy.name?.hi||'',en:copy.name?.en?`${copy.name.en} Copy`:''};openEditor(copy);setTimeout(()=>{const idField=$('productId');if(idField&&typeof nextProductId==='function'){idField.value=nextProductId();idField.readOnly=true}},0);dirty=true;markTitle();toast?.('Product duplicated. Update the copied details and save as a new product.')}
  function enhanceCards(){document.querySelectorAll('.product-item').forEach(card=>{const edit=card.querySelector('[data-edit]');if(!edit||card.querySelector('.duplicate-action'))return;const id=edit.dataset.edit,p=typeof products!=='undefined'?products.find(x=>String(x.id)===String(id)):null;if(p?.status==='hidden'){const meta=card.querySelector('.product-meta');if(meta&&!meta.querySelector('.hidden-badge'))meta.insertAdjacentHTML('beforeend','<span class="badge hidden-badge">Hidden</span>')}const button=document.createElement('button');button.type='button';button.className='duplicate-action';button.textContent='Duplicate';button.dataset.duplicate=id;card.querySelector('.item-actions')?.appendChild(button)})}
  function statusFilter(){if($('phaseBStatusFilter'))return;const cat=$('categoryFilter');if(!cat)return;const s=document.createElement('select');s.id='phaseBStatusFilter';s.className='filter-btn';s.innerHTML='<option value="all">All status</option><option value="active">Active only</option><option value="hidden">Hidden only</option>';cat.insertAdjacentElement('afterend',s);s.addEventListener('change',applyCardStatus)}
  function applyCardStatus(){const wanted=$('phaseBStatusFilter')?.value||'all';document.querySelectorAll('.product-item').forEach(card=>{const edit=card.querySelector('[data-edit]');const p=edit&&typeof products!=='undefined'?products.find(x=>String(x.id)===String(edit.dataset.edit)):null;card.hidden=wanted!=='all'&&((p?.status||'active')!==wanted)});}

  function patchRender(){if(typeof render!=='function'||window.__phaseBRender)return;const original=render;window.__phaseBRender=true;window.render=render=function(){original();enhanceCards();applyCardStatus()}}
  function patchEditor(){if(typeof openEditor!=='function'||window.__phaseBEditor)return;const original=openEditor;window.__phaseBEditor=true;window.openEditor=openEditor=function(p=null){original(p);ensureStatus();const s=$('productStatus');if(s)s.value=p?.status==='hidden'?'hidden':'active';setTimeout(setClean,0)}}
  function patchForm(){const f=$('productForm');if(!f||f.dataset.phaseB)return;f.dataset.phaseB='1';f.addEventListener('input',changed);f.addEventListener('change',changed);}
  function patchSave(){const f=$('productForm');if(!f||f.dataset.phaseBSave)return;f.dataset.phaseBSave='1';f.addEventListener('submit',()=>{setTimeout(()=>{if(!$('productDialog')?.open)setClean()},50),true) }
  function patchPublish(){if(typeof publish!=='function'||window.__phaseBPublish)return;const original=publish;window.__phaseBPublish=true;window.publish=publish=async function(){const errors=validate(typeof products!=='undefined'?products:[]);if(errors.length){toastList(errors);return}return original()}}
  function patchClose(){const d=$('productDialog');if(!d||d.dataset.phaseBClose)return;d.dataset.phaseBClose='1';d.addEventListener('cancel',e=>{if(!dirty)return;if(!confirm('You have unsaved changes. Close without saving?'))e.preventDefault();else dirty=false});[$('closeDialog'),$('cancelBtn')].filter(Boolean).forEach(b=>b.addEventListener('click',e=>{if(!dirty){dirty=false;return}if(!confirm('You have unsaved changes. Close without saving?')){e.preventDefault();e.stopImmediatePropagation()}else dirty=false},{capture:true}))}
  function bindGlobalClicks(){document.addEventListener('click',e=>{const dup=e.target.closest('[data-duplicate]');if(dup){e.preventDefault();duplicateProduct(dup.dataset.duplicate)}})}
  const style=document.createElement('style');style.textContent='.product-preview-dialog{width:min(960px,94vw);max-width:960px;border:0;border-radius:18px;padding:0;box-shadow:0 24px 80px rgba(15,23,42,.25)}.preview-head{display:flex;justify-content:space-between;align-items:flex-start;padding:20px 22px;border-bottom:1px solid #e8edf3}.preview-body{padding:22px;background:#f6f8fb}.public-preview-card{display:grid;grid-template-columns:1fr 1fr;gap:28px;background:#fff;border-radius:18px;padding:22px}.preview-image,.preview-image.placeholder{width:100%;aspect-ratio:1;object-fit:cover;border-radius:14px;background:#eef2f6;display:grid;place-items:center;color:#667085}.public-preview-info h1{font-size:32px;margin:10px 0 4px}.preview-hi-name{color:#667085}.preview-mrp{display:flex;justify-content:space-between;padding:12px 14px;border:1px solid #e4e8ee;border-radius:12px}.preview-section{margin:20px 0}.preview-variants{display:flex;flex-wrap:wrap;gap:8px}.preview-variants span{padding:8px 10px;border:1px solid #e1e5eb;border-radius:999px;font-size:13px}.preview-section ul{padding-left:20px;line-height:1.8}.duplicate-action{margin-left:8px}.hidden-badge{background:#f2f4f7;color:#344054}@media(max-width:700px){.public-preview-card{grid-template-columns:1fr}.duplicate-action{margin-left:0;margin-top:6px}}';document.head.appendChild(style);
  function init(){ensureStatus();patchRender();patchEditor();patchForm();patchSave();patchPublish();patchClose();statusFilter();bindGlobalClicks();const observer=new MutationObserver(()=>{ensureStatus();patchEditor();patchForm();patchClose();enhanceCards()});observer.observe(document.body,{subtree:true,childList:true});window.addEventListener('beforeunload',e=>{if(!dirty)return;e.preventDefault();e.returnValue=''})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
